CI: pin docs nightly version
doc_auto_cfg has been removed

```
error[E0557]: feature has been removed
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.12/src/lib.rs:185:29
    |
185 | #![cfg_attr(docsrs, feature(doc_auto_cfg, doc_cfg_hide), doc(cfg_hide(doc, docsrs)))]
    |                             ^^^^^^^^^^^^ feature has been removed
    |
    = note: removed in CURRENT_RUSTC_VERSION; see <https://github.com/rust-lang/rust/pull/138907> for more information
    = note: merged into `doc_cfg`
```

as a workaround pin to a version predating the change